# Generated by Django 4.2.1 on 2023-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_login_alter_users_fname_alter_users_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
