# Generated by Django 4.2.1 on 2023-05-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_users_email_alter_users_pwd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
